# -*- coding: utf-8 -*-
"""frozenset_bundles.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dgEXhRKkSVA9dugw3uUgsTmKicoYjTcx
"""

# frozenset_bundles.py

"""
1. What is a frozenset?

A frozenset is an immutable version of a set in Python. Once a frozenset is
created, its elements cannot be changed (no add, remove, or update).

Difference between set and frozenset:

set
- Mutable
- Elements can be added or removed
- Cannot be used as a dictionary key

frozenset
- Immutable
- Elements cannot be modified after creation
- Can be used as a dictionary key because it is hashable

When to use frozenset in real systems:

frozenset is useful when you need an immutable collection of unique items.
It is commonly used when sets must be used as dictionary keys or stored
inside other sets. In recommendation systems, bundle pricing, permission
systems, or caching mechanisms, frozenset ensures the combination of items
remains fixed and safe from modification.
"""


from collections import namedtuple
import timeit


# Product structure
Product = namedtuple("Product", ["id", "name", "category", "price"])


# Sample catalog
catalog = [
    Product(1, "Laptop", "Electronics", 75000),
    Product(2, "Smartphone", "Electronics", 50000),
    Product(3, "Headphones", "Electronics", 3000),

    Product(4, "T-Shirt", "Clothing", 800),
    Product(5, "Jeans", "Clothing", 2000),

    Product(6, "Clean Code", "Books", 900),
    Product(7, "Python Crash Course", "Books", 850),

    Product(8, "Coffee Maker", "Home", 2500),
    Product(9, "Blender", "Home", 3000)
]


# Example cart
customer_cart = {catalog[0], catalog[5], catalog[7]}


# 2. Bundle Discount System

bundle_discounts = {
    frozenset({"Electronics", "Books"}): 10,
    frozenset({"Clothing", "Home"}): 5,
    frozenset({"Electronics", "Home"}): 8
}


# 3. Bundle Checker Function

def check_bundle_discount(cart):
    categories_in_cart = {product.category for product in cart}

    for bundle, discount in bundle_discounts.items():
        if bundle.issubset(categories_in_cart):
            return discount

    return 0


discount = check_bundle_discount(customer_cart)

print("Applicable Discount:", discount, "%")


# 4. Performance Benchmark (set vs frozenset)

set_time = timeit.timeit(
    "set(['Electronics','Books'])",
    number=100000
)

frozenset_time = timeit.timeit(
    "frozenset(['Electronics','Books'])",
    number=100000
)

print("\nPerformance Benchmark (100000 iterations)")
print("Set creation time:", set_time)
print("Frozenset creation time:", frozenset_time)


"""
Results Explanation

Both set and frozenset creation times are very similar. However, frozenset may
be slightly slower because it creates an immutable structure.

Key takeaway:
- set is better for mutable collections
- frozenset is ideal when immutability is required and when sets must be used
  as dictionary keys or elements of other sets.
"""

