# -*- coding: utf-8 -*-
"""product_analytics.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vmDBQcoZfcM6x4-2ezo5g0SYbFaJIbF5
"""

# Product Analytics Tool

from collections import namedtuple

# 1. Define Named Tuple
Product = namedtuple("Product", ["id", "name", "category", "price"])


# 2. Create Product Catalog
catalog = [
    Product(1, "Laptop", "Electronics", 75000),
    Product(2, "Smartphone", "Electronics", 50000),
    Product(3, "Headphones", "Electronics", 3000),
    Product(4, "Smartwatch", "Electronics", 12000),

    Product(5, "T-Shirt", "Clothing", 800),
    Product(6, "Jeans", "Clothing", 2000),
    Product(7, "Jacket", "Clothing", 3500),
    Product(8, "Sneakers", "Clothing", 4000),

    Product(9, "Clean Code", "Books", 900),
    Product(10, "Python Crash Course", "Books", 850),
    Product(11, "Atomic Habits", "Books", 700),

    Product(12, "Coffee Maker", "Home", 2500),
    Product(13, "Blender", "Home", 3000),
    Product(14, "Desk Lamp", "Home", 1200),
    Product(15, "Air Fryer", "Home", 6000)
]


# 3. Customer Cart Sets
customer_1_cart = {catalog[0], catalog[1], catalog[4], catalog[8]}
customer_2_cart = {catalog[0], catalog[2], catalog[5], catalog[9]}
customer_3_cart = {catalog[0], catalog[3], catalog[6], catalog[10]}
customer_4_cart = {catalog[0], catalog[7], catalog[8], catalog[11]}
customer_5_cart = {catalog[0], catalog[2], catalog[4], catalog[12]}

all_carts = [
    customer_1_cart,
    customer_2_cart,
    customer_3_cart,
    customer_4_cart,
    customer_5_cart
]


# 4a. Bestsellers (Products in ALL carts)
bestsellers = set.intersection(*all_carts)
print("Bestsellers:")
print({p.name for p in bestsellers})


# 4b. Catalog Reach (Products in ANY cart)
catalog_reach = set.union(*all_carts)
print("\nProducts purchased by any customer:")
print({p.name for p in catalog_reach})


# 4c. Exclusive purchases by Customer 1
other_carts = set.union(customer_2_cart, customer_3_cart, customer_4_cart, customer_5_cart)
exclusive_customer1 = customer_1_cart - other_carts

print("\nExclusive purchases by Customer 1:")
print({p.name for p in exclusive_customer1})


# 5. Product Recommendation Function
def recommend_products(customer_cart, all_carts):
    other_products = set.union(*all_carts)
    recommendations = other_products - customer_cart
    return {p.name for p in recommendations}


print("\nRecommendations for Customer 1:")
print(recommend_products(customer_1_cart, all_carts))


# 6. Category Summary Function
def category_summary(catalog):
    categories = {product.category for product in catalog}

    summary = {
        category: {p.name for p in catalog if p.category == category}
        for category in categories
    }

    return summary


print("\nCategory Summary:")
print(category_summary(catalog))

